<?php
/*$g_translations = array (
		"fr_fr" => array (
				//Common data
				"Interval" => "Interval",
				"Type" => "Type",
				"Status" => "Status",
				"Customer" => "Client",
				"Supplier" => "Fournisseur",
				"Supplier Code" => "Code fournisseur",
				"Customers" => "Clients",
				"Suppliers" => "Fournisseurs",
				"IdProf1" => "SIREN",
				"Date" => "Date",
				"Yes" => "Oui",
				"No" => "Non",
				"Total ET" => "Total HT",
				"Total Ttc" => "Total",
				"Vat" => "TVA",
				"VAT" => "TVA",
				"Price ET" => "Prix HT",
				"Prix IT" => "Total",
				"Total IT" => "Total",
				"Average" => "Moyen",
				"Paid" => "Paye",
				"Show" => "Montrer",
				"Products" => "Produits",
				"Services" => "Services",
				"Description" => "Description",
				"Warehouse" => "Entrepot",
				"Product" => "Produit",
				"Service" => "Service",
				"Product/Service" => "Produit/Service",
				"Category" => "Categorie",
				"Customer Category" => "Categorie de clients",
				"Product Category" => "Categorie de produit",
				"Reference" => "Reference",
				"Quantity" => "Quantite",
				"Qty." => "Qty.",
				"Qty" => "Qty.",
				"Avg. Price" => "Prix moyen",
				"Name" => "Nom",
				"Order" => "Commande",
				"Label" => "Etiquette",
				"Canceled" => "Annule",
				"Envoyed" => "Envoye",
				"Processed" => "Traite",
				"Invoiced" => "Facture",
				"Hide" => "Cacher",
				"Sales representative" => "Representant des ventes",
				"Nom" => "Nom",
				"Adress" => "Adresse",
				"City" => "Ville",
				"Phone" => "Telephone",
				"Fax" => "Fax",
				"Email" => "E-Mail",
				"First Name" => "Prenom",
				"Last Name" => "Nom",
				"Company" => "Company",
				"Post" => "Poste",
				"Mobile" => "Mobile",
				"User" => "Utilisateur",
				"Hours" => "Heures",				
				"Sale Price" => "Prix de vente",
				"Buy Price" => "Acheter prix",
				"Margin" => "Marge",
				"Note Private" => "Note privee",
				"Hide Columns (No PDF)" => "Masquer les colonnes (Pas PDF)",

				//Months
				"Month" => "Mois",
				"January" => "Janvier",
				"February" => "Fevrier",
				"March" => "Mars",
				"April" => "Avril",
				"May" => "Mai",
				"June" => "Juin",
				"July" => "Juillet",
				"August" => "Aout",
				"September" => "Septembre",
				"October" => "Octobre",
				"November" => "Novembre",
				"December" => "Decembre",
				"No Data Matched Your Criteria" => "Pas de donnees",
				"Year" => "Anne",				

				//Invoices
				"Customers invoices" => "Factures aux clients",
				"Sales summary" => "Sommaire des ventes",
				"Supplier invoices" => "Factures des fournisseurs",
				"Purchases summary" => "Sommaire des achats",
				"Sales Tax detail" => "Ventilation TVA ventes",
				"Purchases Tax detail" => "Ventilation TVA achats",
				"Margin By Customer" => "Marge par client",
				"Margin By Sales Representative" => "Marge par representant des ventes",
				"Cash Balance" => "Balance de caisse",
				"Commitment Balance" => "Balance d'engagement",
				"Income By Customer" => "Recette par client",
				"Sales By Sales Representative" => "Ventes par representant des ventes",
				"Invoice" => "Facture",
				"Invoices" => "Factures",
				"Standard" => "Standard",
				"Replacement" => "Replacement",
				"Credit Note" => "Note de credit",
				"Deposit" => "d'acompte",
				"Proform" => "Proforma",
				"Draft" => "Brouillon",
				"Validated" => "Valide",
				"Paid (total or parcial)" => "Paied (total ou partiel)",
				"Abandoned" => "Abandonne",
				"Charged" => "Charge",
				"Facture" => "Facture",
				"Total invoiced" => "Total facture",
				"Average invoice" => "Moyen par facture",
				"Income" => "Recettes",
				"Expense" => "Depenses",
				
				//Products
				"Products list" => "Liste des produits",
				"Products Stocks" => "Stocks de produits",
				"Stock alerts" => "Alertes stock",
				"Products sales" => "Ventes de produits",
				"Sales details" => "Ventilation des ventes",
				"Undelivered products" => "Produits pendants",
				"Ordered products" => "Produits commandes",
				"Stock Alert" => "Alertes stock",
				"Margin By Product" => "Marge par produit",
				"Stocktotal" => "Total",
				"Customer Code" => "Code client",
				"Qty Ordered" => "Qty. Demande",
				"Qty Shipped" => "Qty. Envoye",
				"Pending" => "Pendant",
				"Input Stock Value" => "PMP",
				"Value" => "Valeur",
				"Entry" => "Entree",
				"Output" => "Sortie",
				"Stocks Value" => "Valeur Stock",
				"Stocks Moviments" => "Mouvement Stock",
				
				//Propals
				"Customer proposals" => "Propales aux clients",
				"Opened" => "Ouvert",
				"Signed" => "Signe",
				"Not signed" => "Non signe",
				"Billed" => "Facture",
				"Proposals not firmed" => "Prop. com. not signed",
				
				//Orders
				"Customer orders" => "Commandes des clients",
				"Suppliers Orders" => "Commandes aux fournisseurs",
				"Approved" => "Approuve",
				"In process" => "En cours",
				"Partially received" => "Reçue partiellement",
				"Received" => "Reçu",
				"Annuled" => "Annule",
				"Not received" => "Pas reçu",
				"Rejected" => "Rejete",
				"Entry details" => "Details de l'entre",
				"Output details" => "Details de sortie",

				//Contracts
				"Active Contracts" => "Contrats actifs",
				"Expiring Contracts" => "Contrats expirant",
				"Start Prev" => "Prevue mise",
				"Start" => "Effective mise",
				"End Prev" => "Prevue fin",
				"End" => "Effective fin",
				"Active" => "Actif",
				"Inactive" => "Inactif",
				"Closed" => "Ferme",
				
				//Intervention
				"Intervention" => "Fichinter",
				"Interventions" => "Fichinters",
				"Interventions Details" => "Sommaire de fichinters",
				"Duration" => "Duree",
				
				//Agenda
				"Title" => "Titre",
				"Date start" => "Début",
				"Date end" => "Fin",
				"User action" => "Assigné à",
				"User author" => "Créé par",
				"Not Applicable" => "Non applicable",
				"To Do" => "À faire",
				"In Process" => "En cours",
				"Done" => "Terminé",
				"Phone call" =>"Appel téléphonique",
				"Send fax" =>"Envoi fax",
				"Send proposal by mail" =>"Envoi proposition par email",
				"Send Email" =>"Envoi email",
				"Meetings" =>"Rendez-vous",
				"Intervention on site" =>"Intervention sur site",
				"Send customer invoice by mail" =>"Envoi facture client par email",
				"Send customer invoice by mail (reminder)" =>"Relance facture client par email",
				"Close" =>"Clôture",
				"Send mass email" =>"Envoi emailing masse",
				"Send customer order by mail" =>"Envoi commande client par email",
				"Send shipping by mail" =>"Envoi bon d'expédition par email",
				"Send supplier order by mail" =>"Envoi commande fournisseur par email",
				"Send supplier invoice by mail" =>"Envoi facture fournisseur par email",
				"Other" =>"Autre",
				"Other (automatically inserted events)" =>"Autre (evênements insérés automatiquement)",
				"Manually inserted events" =>"Événements insérés manuellement",
				"Automatically inserted events" =>"Événements insérés automatiquement",
				
				//Thirds
				"List of Third Parties" => "Liste des tiers",
				"List of contacts" => "Liste des contacts",

				//Projects
				"Project" => "Projet",
				"Task" => "Tache",
				"List of projects" => "Liste des projets",
				"Staff costs" => "Frais de personnel",
				"Margin of projects" => "Marge par projet",
				
				//Batch
				"Shipping" => "Expedition",
				"Shipping Date" => "Date d'expedition",
				"Batch" => "Lot",
				"Expiration" => "Expiration",
				"Max Sale Date" => "Max date vente",
				"Batch Sales" => "Vente lots",
				"Batch Purchases" => "Achater lots",
				"Order Date" => "Date commande",

				//Ecommerce
				"Customer Ecommerce Orders" => "Commandes clients Ecommerce",
				"Ecommerce Sales Tax Detail" => "Ventilation TVA ventes Ecommerce",
				"Ecommerce Customers invoices" => "Factures Clients Ecommerce",
				"Product Sales Ecommerce" => "Ventes des produits Ecommerce",
				"Ecommerce Sales Summary" => "Sommaire des ventes Ecommerce",
				"Shop" => "Boutique"
				
			),
		"es_es" => array (
				//Common data
				"Interval" => "Intervalo",
				"Type" => "Tipo",
				"Status" => "Estado",
				"Customer" => "Cliente",
				"Supplier" => "Proveedor",
				"Customers" => "Clientes",
				"Suppliers" => "Proveedores",
				"Supplier Code" => "Codigo proveedor",
				"IdProf1" => "CIF/NIF",
				"Date" => "Fecha",
				"Yes" => "Si",
				"No" => "No",
				"Total ET" => "Base imp.",
				"Total Ttc" => "Total",
				"Vat" => "IVA",
				"VAT" => "IVA",
				"Price ET" => "Base imp.",
				"Prix IT" => "Total",
				"Total IT" => "Total",
				"Average" => "Media",
				"Paid" => "Pagada",
				"Show" => "Mostrar",
				"Products" => "Productos",
				"Services" => "Servicios",
				"Description" => "Descripcion",
				"Warehouse" => "Almacen",
				"Product" => "Producto",
				"Service" => "Servicio",
				"Product/Service" => "Producto/Servicio",
				"Category" => "Categoria",
				"Customer Category" => "Categoria de cliente",
				"Product Category" => "Categoria de producto",
				"Reference" => "Referencia",
				"Quantity" => "Cantidad",
				"Qty." => "Cant.",
				"Qty" => "Cant.",
				"Avg. Price" => "Precio medio",
				"Name" => "Nombre",
				"Order" => "Pedido",
				"Label" => "Etiqueta",
				"Canceled" => "Cancelado",
				"Envoyed" => "Enviado",
				"Processed" => "Procesado",
				"Invoiced" => "Facturado",
				"Hide" => "Ocultar",
				"Sales representative" => "Comercial",
				"Nom" => "Nombre",
				"Adress" => "Direccion",
				"City" => "Poblacion",
				"Phone" => "Telefono",
				"Fax" => "Fax",
				"Email" => "E-Mail",
				"First Name" => "Nombre",
				"Last Name" => "Apellidos",
				"Company" => "Empresa",
				"Post" => "Puesto",
				"Mobile" => "Movil",
				"Page pageno()" => "Pagina pageno()",
				"User" => "Usuario",
				"Hours" => "Horas",	
				"Sale Price" => "Precio de venta",
				"Buy Price" => "Precio de compra",
				"Margin" => "Margen",
				"Note Private" => "Nota privada",
				"Hide Columns (No PDF)" => "Ocultar las columnas (No PDF)",
				
				//Months
				"Month" => "Mes",
				"January" => "Enero",
				"February" => "Febrero",
				"March" => "Marzo",
				"April" => "Abril",
				"May" => "Mayo",
				"June" => "Junio",
				"July" => "Julio",
				"August" => "Agosto",
				"September" => "Septiembre",
				"October" => "Octubre",
				"November" => "Noviembre",
				"December" => "Diciembre",
				"No Data Matched Your Criteria" => "No hay datos disponibles",
				"Year" => "Año",
				
				//Invoices
				"Customers invoices" => "Facturas a clientes",
				"Sales summary" => "Resumen de ventas",
				"Supplier invoices" => "Facturas de proveedores",
				"Purchases summary" => "Resumen de compras",
				"Sales Tax detail" => "Desglose IVA ventas",
				"Purchases Tax detail" => "Desglose IVA compras",
				"Margin By Customer" => "Margen por cliente",
				"Margin By Sales Representative" => "Margen por comercial",
				"Cash Balance" => "Balance de caja",
				"Commitment Balance" => "Balance de compromiso",
				"Income By Customer" => "Ingresos por cliente",
				"Sales By Sales Representative" => "Ventas por comercial",
				"Invoice" => "Factura",
				"Invoices" => "Facturas",
				"Standard" => "Estandard",
				"Replacement" => "Rectificativa",
				"Credit Note" => "Abono",
				"Deposit" => "Anticipo",
				"Proform" => "Proforma",
				"Draft" => "Borrador",
				"Validated" => "Validada",
				"Paid (total or parcial)" => "Pagada (total o parcial)",
				"Abandoned" => "Abandonada",
				"Charged" => "Cobrada",
				"Facture" => "Factura",
				"Total invoiced" => "Total facturado",
				"Average invoice" => "Media por factura",
				"Income" => "Ingresos",
				"Expense" => "Gastos",
				"Outstanding debits" => "Domiciliaciones pendientes",
				
				//Products
				"Products list" => "Listado de productos",
				"Products Stocks" => "Stocks de productos",
				"Stock alerts" => "Alertas de stock",
				"Products sales" => "Ventas de productos",
				"Sales details" => "Desglose de ventas",
				"Undelivered products" => "Productos por enviar",
				"Ordered products" => "Productos pedidos",
				"Stock Alert" => "Alerta de stock",
				"Margin By Product" => "Margen por producto",
				"Stocktotal" => "Total",
				"Customer Code" => "Codigo Cliente",
				"Qty Ordered" => "Cant. Pedida",
				"Qty Shipped" => "Cant. Enviada",
				"Pending" => "Pendiente",
				"Input Stock Value" => "PMP",
				"Value" => "Valor",
				"Entry" => "Entrada",
				"Output" => "Salida",
				"Stocks Value" => "Valoración Stock",
				"Stocks Moviments" => "Movimiento Stock",
				
				//Propals
				"Customer proposals" => "Presupuestos a clientes",
				"Opened" => "Abierto",
				"Signed" => "Firmado",
				"Not signed" => "No firmado",
				"Billed" => "Facturado",
				"Proposals not firmed" => "Presupuestos no firmados",
				
				//Orders
				"Customer orders" => "Pedidos de clientes",
				"Suppliers Orders" => "Pedidos a proveedores",
				"Approved" => "Aprobado",
				"In process" => "En proceso",
				"Partially received" => "Recibido parcialmente",
				"Received" => "Recibido",
				"Annuled" => "Anulado",
				"Not received" => "No recibido",
				"Rejected" => "Rechazado",
				"Entry details" => "Desglose entradas",
				"Output details" => "Desglose suministros",

				//Contracts
				"Active Contracts" => "Contratos activos",
				"Expiring Contracts" => "Contratos a expirar",
				"Start Prev" => "Inicio previsto",
				"Start" => "Inicio real",
				"End Prev" => "Fin previsto",
				"End" => "Fin real",
				"Active" => "Activo",
				"Inactive" => "Inactivo",
				"Closed" => "Cerrado",
				
				//Intervention
				"Intervention" => "Intervencion",
				"Interventions" => "Intervenciones",
				"Interventions Details" => "Desglose de intervenciones",
				"Duration" => "Duracion",
				
				//Agenda
				"Title" => "Asunto",
				"Date start" => "Inicio",
				"Date end" => "Fin",
				"User action" => "Asignado a",
				"User author" => "Creado por",
				"Not Applicable" => "No aplicable",
				"To Do" => "No empezada",
				"In Process" => "Empezado",
				"Done" => "Terminado",
				"Phone call" =>"Llamada telefónica",
				"Send fax" =>"Envío Fax",
				"Send proposal by mail" =>"Envío presupuesto por correo",
				"Send Email" =>"Envío E-Mail",
				"Meetings" =>"Cita",
				"Intervention on site" =>"Intervención in situ",
				"Send customer invoice by mail" =>"Envío factura a cliente por correo",
				"Send customer invoice by mail (reminder)" =>"Recordatorio factura a cliente por correo",
				"Close" =>"Cierre",
				"Send mass email" =>"Envío mailing masivo",
				"Send customer order by mail" =>"Envío pedido de cliente por correo",
				"Send shipping by mail" =>"Envío expedición por correo",
				"Send supplier order by mail" =>"Envío pedido a proveedor por correo",
				"Send supplier invoice by mail" =>"Envío factura de proveedor por correo",
				"Other" =>"Otra",
				"Other (automatically inserted events)" =>"Otra (eventos insertados automáticamente)",
				"Manually inserted events" =>"Eventos creados manualmente",
				"Automatically inserted events" =>"Eventos creados automáticamente",
				
				//Thirds
				"List of Third Parties" => "Listado de terceros",
				"List of contacts" => "Listado de contactos",

				//Projects
				"Project" => "Proyecto",
				"Task" => "Tarea",
				"List of projects" => "Listado de proyectos",
				"Staff costs" => "Gastos de personal",
				"Margin of projects" => "Margen proyectos",
				"Profit" => "Rentabilidad",
				
				//Batch
				"Shipping" => "Envio",
				"Shipping Date" => "Fecha envio",
				"Batch" => "Lote",
				"Expiration" => "Caducidad",
				"Max Sale Date" => "Fecha máxima de venta",
				"Batch Sales" => "Venta lotes",
				"Batch Purchases" => "Compra lotes",
				"Order Date" => "Fecha pedido",

				//Ecommerce
				"Customer Ecommerce Orders" => "Pedidos Clientes Ecommerce",
				"Ecommerce Sales Tax Detail" => "Desglose IVA ventas Ecommerce",
				"Ecommerce Customers invoices" => "Facturas Clientes Ecommerce",
				"Product Sales Ecommerce" => "Venta productos Ecommerce",
				"Ecommerce Sales Summary" => "Resumen ventas Ecommerce",
				"Shop" => "Tienda"
			),
		"ca_es" => array (
				//Common data
				"Interval" => "Interval",
				"Type" => "Tipus",
				"Status" => "Estat",
				"Customer" => "Client",
				"Supplier" => "Proveidor",
				"Supplier Code" => "Codi proveïdor",
				"Customers" => "Clients",
				"Suppliers" => "Proveidors",
				"IdProf1" => "CIF/NIF",
				"Date" => "Data",
				"Yes" => "Si",
				"No" => "No",
				"Total ET" => "Base imp.",
				"Total Ttc" => "Total",
				"Vat" => "IVA",
				"VAT" => "IVA",
				"Price ET" => "Base imp.",
				"Prix IT" => "Total",
				"Total IT" => "Total",
				"Average" => "Mitja",
				"Paid" => "Pagada",
				"Show" => "Mostrar",
				"Products" => "Productes",
				"Services" => "Servicis",
				"Description" => "Descripcio",
				"Warehouse" => "Magatzem",
				"Product" => "Producte",
				"Service" => "Servici",
				"Product/Service" => "Producte/Servici",
				"Category" => "Categoria",
				"Customer Category" => "Categoria de client",
				"Product Category" => "Categoria de producte",
				"Reference" => "Referencia",
				"Quantity" => "Quantitat",
				"Qty." => "Quant.",
				"Qty" => "Quant.",
				"Avg. Price" => "Preu mig",
				"Name" => "Nom",
				"Order" => "Comanda",
				"Label" => "Etiqueta",
				"Canceled" => "Cancelat",
				"Envoyed" => "Enviat",
				"Processed" => "Processat",
				"Invoiced" => "Facturat",
				"Hide" => "Ocultar",
				"Sales representative" => "Comercial",
				"Nom" => "Nom",
				"Adress" => "Direccio",
				"City" => "Poblacio",
				"Phone" => "Telefon",
				"Fax" => "Fax",
				"Email" => "E-Mail",
				"First Name" => "Nom",
				"Last Name" => "Cognoms",
				"Company" => "Empresa",
				"Post" => "Carrec",
				"Mobile" => "Mobil",
				"Page pageno()" => "Pagina pageno()",
				"User" => "Usuari",
				"Hours" => "Hores",
				"Sale Price" => "Preu de venda",
				"Buy Price" => "Preu de compra",
				"Margin" => "Marge",
				"Note Private" => "Nota privada",
				"Hide Columns (No PDF)" => "Ocultar les columnes (No PDF)",
		
				//Months
				"Month" => "Mes",
				"January" => "Gener",
				"February" => "Febrer",
				"March" => "Març",
				"April" => "Abril",
				"May" => "Maig",
				"June" => "Juny",
				"July" => "Juliol",
				"August" => "Agost",
				"September" => "Setembre",
				"October" => "Octubre",
				"November" => "Novembre",
				"December" => "Desembre",
				"No Data Matched Your Criteria" => "No hi ha dades disponibles",
				"Year" => "Any",
		
				//Invoices
				"Customers invoices" => "Factures a clients",
				"Sales summary" => "Resum de vendes",
				"Supplier invoices" => "Factures de proveidors",
				"Purchases summary" => "Resum de compres",
				"Sales Tax detail" => "Desglossament IVA vendes",
				"Purchases Tax detail" => "Desglossament IVA compres",
				"Margin By Customer" => "Marge per client",
				"Margin By Sales Representative" => "Marge per comercial",
				"Cash Balance" => "Balanç de caixa",
				"Commitment Balance" => "Balanç de compromís",
				"Income By Customer" => "Ingressos per client",
				"Sales By Sales Representative" => "Ventes per comercial",
				"Invoice" => "Factura",
				"Invoices" => "Factures",
				"Standard" => "Estandard",
				"Replacement" => "Rectificativa",
				"Credit Note" => "Abonament",
				"Deposit" => "Bestreta",
				"Proform" => "Proforma",
				"Draft" => "Esborrany",
				"Validated" => "Validada",
				"Paid (total or parcial)" => "Pagada (total o parcial)",
				"Abandoned" => "Abandonada",
				"Charged" => "Cobrada",
				"Facture" => "Factura",
				"Total invoiced" => "Total facturat",
				"Average invoice" => "Mitja per factura",
				"Income" => "Ingressos",
				"Expense" => "Despeses",
		
				//Products
				"Products list" => "Llistat de productes",
				"Products Stocks" => "Stocks de productes",
				"Stock alerts" => "Alertes de stock",
				"Products sales" => "Vendes de productes",
				"Sales details" => "Desglossament de vendes",
				"Undelivered products" => "Productes per enviar",
				"Ordered products" => "Productes demanats",
				"Stock Alert" => "Alerta de stock",
				"Margin By Product" => "Marge per producte",
				"Stocktotal" => "Total",
				"Customer Code" => "Codi Client",
				"Qty Ordered" => "Quant. Demanada",
				"Qty Shipped" => "Quant. Enviada",
				"Pending" => "Pendent",
				"Input Stock Value" => "PMP",
				"Value" => "Valor",
				"Entry" => "Entrada",
				"Output" => "Sortida",
				"Stocks Value" => "Valoració Stock",
				"Stocks Moviments" => "Moviments Stock",
		
				//Propals
				"Customer proposals" => "Pressupostos a clients",
				"Opened" => "Obert",
				"Signed" => "Firmat",
				"Not signed" => "No firmat",
				"Billed" => "Facturat",
				"Proposals not firmed" => "Pressupostos no firmats",
		
				//Orders
				"Customer orders" => "Comandes de clients",
				"Suppliers Orders" => "Comandes a proveidors",
				"Approved" => "Aprovat",
				"In process" => "En proces",
				"Partially received" => "Rebut parcialment",
				"Received" => "Rebut",
				"Annuled" => "Anulat",
				"Not received" => "No rebut",
				"Rejected" => "Rebutjat",
				"Entry details" => "Desglossament d'entrades",
				"Output details" => "Desglossament suministres",
		
				//Contracts
				"Active Contracts" => "Contractes actius",
				"Expiring Contracts" => "Contractes a expirar",
				"Start Prev" => "Inici previst",
				"Start" => "Inici real",
				"End Prev" => "Fin previst",
				"End" => "Fin real",
				"Active" => "Actiu",
				"Inactive" => "Inactiu",
				"Closed" => "Tancat",
				
				//Intervention
				"Intervention" => "Intervencio",
				"Interventions" => "Intervencios",
				"Interventions Details" => "Desglossament d'intervencions",
				"Duration" => "Duracio",
				
				//Agenda
				"Title" => "Títol",
				"Date start" => "Inici",
				"Date end" => "Fi",
				"User action" => "Assignat a",
				"User author" => "Creat per",
				"Not Applicable" => "No aplicable",
				"To Do" => "No començat",
				"In Process" => "Començat",
				"Done" => "Acabat",
				"Phone call" =>"Trucada telefònica",
				"Send fax" =>"Enviament Fax",
				"Send proposal by mail" =>"Enviament pressupost per correu",
				"Send Email" =>"Enviament E-Mail",
				"Meetings" =>"Cita",
				"Intervention on site" =>"Intervenció in situ",
				"Send customer invoice by mail" =>"Enviament factura a client per correu",
				"Send customer invoice by mail (reminder)" =>"Recordatori factura a client per correu",
				"Close" =>"Tancament",
				"Send mass email" =>"Enviament mailing massiu",
				"Send customer order by mail" =>"Enviament comanda de client per correu",
				"Send shipping by mail" =>"Enviament expedició per correu",
				"Send supplier order by mail" =>"Enviament comanda a proveïdor per correu",
				"Send supplier invoice by mail" =>"Enviament factura de proveïdor per correu",
				"Other" =>"Altra",
				"Other (automatically inserted events)" =>"Altra (esdeveniments inserits automàticament)",
				"Manually inserted events" =>"Esdeveniments creats manualment",
				"Automatically inserted events" =>"Esdeveniments creats automàticament",
				
				//Thirds
				"List of Third Parties" => "Llistat de tercers",
				"List of contacts" => "Llistat de contactes",
		
				//Projects
				"Project" => "Projecte",
				"Task" => "Tasca",
				"List of projects" => "Llistat de projectes",
				"Staff costs" => "Despeses de personal",
				"Margin of projects" => "Marge projectes",
				
				//Batch
				"Shipping" => "Enviament",
				"Shipping Date" => "Data enviament",
				"Batch" => "Lot",
				"Expiration" => "Caducitat",
				"Max Sale Date" => "Data màxima de venta",
				"Batch Sales" => "Venta lots",
				"Batch Purchases" => "Compra lots",
				"Order Date" => "Data comanda",
		
				//Ecommerce
				"Customer Ecommerce Orders" => "Comandes Clients Ecommerce",
				"Ecommerce Sales Tax Detail" => "Desglossament IVA vendes Ecommerce",
				"Ecommerce Customers invoices" => "Factures Clients Ecommerce",
				"Product Sales Ecommerce" => "Venda productes Ecommerce",
				"Ecommerce Sales Summary" => "Resum vendes Ecommerce",
				"Shop" => "Tenda"
		)
		);*/
/*
$g_report_desc = array ( "fr_fr" => array (
		"tut2_loanhistory.xml" =>
'
La <b>Report Du Emplacement Histoire</b> produit une liste des filmes bourree du libraire groupee par membre.
<p>
Il montre le suivant :-
<p>
1. 
 of adding a date range criteria by reporting on films that have been borrowed between the specified dates. It also demonstrates the use of setting date range defaults.
<p>
2. use of a LIST type criteria item
<p>
3. conditional assignment by displaying "UNRETURNED" in the return date column instead of a normal blank
'
			)
		);
		*/
?>
